import { Roboto_Slab, Outfit } from "next/font/google"
import { ClerkProvider, RedirectToSignIn, useAuth } from "@clerk/nextjs";

import Provider from "./provider";

import "./globals.css";
import { Toaster } from "../components/ui/sonner";


const outfit = Outfit({ subsets: ['latin'] })
const roboto = Roboto_Slab({ subsets: ['greek'] })
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  const { isLoaded, isSignedIn } = useAuth
  if (!isSignedIn) {
    return <RedirectToSignIn />; // Redirect to sign-in if not authenticated
  }
  return (
    <ClerkProvider>
      <html lang="en">
        <body
          className={`${outfit.className} ${roboto.className}`}
        >
          <Provider>
            {children}
          </Provider>
          <Toaster />
        </body>
      </html>
    </ClerkProvider>
  );
}
